package edu.mayo.kmdp.kdcaci.knew.terms;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import edu.mayo.ontology.taxonomies.propositionalconcepts.PropositionalConceptsSeries;
import edu.mayo.ontology.taxonomies.propositionalconcepts.snapshot.PropositionalConcepts;
import org.junit.jupiter.api.Test;

public class TerminologyConsumerTest {

  @Test
  public void testMerAfib() {

    assertNotNull(PropositionalConceptsSeries.Patient);
    assertNotNull(PropositionalConceptsSeries.Has_Atrial_Fibrillation);
    assertNotNull(
        PropositionalConceptsSeries.Has_Bleeding_Disorder_Excluding_Hypercoagulative_Disorder);
    assertNotNull(PropositionalConceptsSeries.History_Of_Central_Nervous_System_Bleeding);
    assertNotNull(PropositionalConceptsSeries.History_Of_GI_Bleeding);
    assertNotNull(PropositionalConceptsSeries.On_Anticoagulant);
    assertNotNull(PropositionalConceptsSeries.History_Of_Congestive_Heart_Failure);
    assertNotNull(PropositionalConceptsSeries.History_Of_Hypertension);
    assertNotNull(PropositionalConceptsSeries.History_Of_Stroke);
    assertNotNull(PropositionalConceptsSeries.History_Of_Transient_Ischemic_Attack);
    assertNotNull(PropositionalConceptsSeries.History_Of_Thromboembolism);
    assertNotNull(PropositionalConceptsSeries.History_Of_Coronary_Artery_Disease);
    assertNotNull(PropositionalConceptsSeries.History_Of_Peripheral_Arterial_Disease);
    assertNotNull(PropositionalConceptsSeries.Has_Diabetes_Mellitus);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_Blood_Pressure);
    assertNotNull(PropositionalConceptsSeries.On_Dialysis);
    assertNotNull(PropositionalConceptsSeries.On_Peritoneal_Dialysis);
    assertNotNull(PropositionalConceptsSeries.On_Hemodialysis);
    assertNotNull(PropositionalConceptsSeries.Has_Transplanted_Kidney);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_Creatinine);
    assertNotNull(PropositionalConceptsSeries.Has_Cirrhosis);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_Bilirubin);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_AST_GOT);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_ALT_GPT);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_Alkaline_Phosphatase);
    assertNotNull(PropositionalConceptsSeries.Prior_INR);
    assertNotNull(PropositionalConceptsSeries.On_Antiplatelet_Agents);
    assertNotNull(PropositionalConceptsSeries.On_NSAIDs);
    assertNotNull(PropositionalConceptsSeries.On_NSAIDS_Contraindicated_In_HFrEF);
    assertNotNull(PropositionalConceptsSeries.Has_Alcohol_Abuse);
    assertNotNull(PropositionalConceptsSeries.Has_Drug_Abuse);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_Amount_Of_Alcohol_Consumption);
    assertNotNull(PropositionalConceptsSeries.On_Dialysis_Is);
    assertNotNull(PropositionalConceptsSeries.On_Peritoneal_Dialysis_Is);
    assertNotNull(PropositionalConceptsSeries.On_Hemodialysis_Is);
    assertNotNull(PropositionalConceptsSeries.Has_Transplanted_Kidney_Is);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_Creatinine_Value_Of);
    assertNotNull(PropositionalConceptsSeries.Has_Cirrhosis_Is);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_Bilirubin_Value_Of);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_AST_GOT_Value_Of);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_Alkaline_Phosphatase_Value_Of);
    assertNotNull(PropositionalConceptsSeries.Has_Elevated_ALP_Is);
    assertNotNull(PropositionalConceptsSeries.Has_Elevated_AST_Is);
    assertNotNull(PropositionalConceptsSeries.Has_Elevated_ALT_Is);
    assertNotNull(PropositionalConceptsSeries.Has_Elevated_Bilirubin_Is);
    assertNotNull(PropositionalConceptsSeries.On_Antiplatelet_Agents_Is);
    assertNotNull(PropositionalConceptsSeries.On_NSAID_Is);
    assertNotNull(PropositionalConceptsSeries.Has_Alcohol_Abuse_Is);
    assertNotNull(PropositionalConceptsSeries.Has_Drug_Abuse_Is);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_Amount_Of_Alcohol_Consumption_Value_Of);
    assertNotNull(PropositionalConceptsSeries.Age_Value_Of);
    assertNotNull(PropositionalConceptsSeries.Age_Within_Defined_Range_Kind_Of);
    assertNotNull(PropositionalConceptsSeries.Age_Within_Defined_Range_Is);
    assertNotNull(PropositionalConceptsSeries.Sex_Kind_Of);
    assertNotNull(PropositionalConceptsSeries.History_Of_Congestive_Heart_Failure_Is);
    assertNotNull(PropositionalConceptsSeries.History_Of_Hypertension_Is);
    assertNotNull(
        PropositionalConceptsSeries.History_Of_Stroke_Transient_Ischemic_Attack_Or_Thromboembolism_Is);
    assertNotNull(PropositionalConceptsSeries.History_Of_Vascular_Disease_Is);
    assertNotNull(PropositionalConceptsSeries.Has_Diabetes_Mellitus_Is);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_Systolic_Blood_Pressure_Value_Of);
    assertNotNull(PropositionalConceptsSeries.Has_Kidney_Disease_Is);
    assertNotNull(PropositionalConceptsSeries.Has_Liver_Disease_Is);
    assertNotNull(PropositionalConceptsSeries.History_Of_Stroke_Is);
    assertNotNull(PropositionalConceptsSeries.Has_Labile_INR_Is);
    assertNotNull(PropositionalConceptsSeries.Prior_Major_Bleeding_Or_Predisposition_To_Bleeding_Is);
    assertNotNull(PropositionalConceptsSeries.On_Medication_Predisposing_To_Bleeding_Is);
    assertNotNull(PropositionalConceptsSeries.History_Of_Alcohol_Or_Drug_Usage_Is);
    assertNotNull(PropositionalConceptsSeries.Current_CHA2DS2_VASc_Score_Value_Of);
    assertNotNull(PropositionalConceptsSeries.Current_HAS_BLED_Score_Value_Of);
  }


  @Test
  public void testMerHeartFailure() {

    assertNotNull(PropositionalConceptsSeries.Patient);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_Blood_Pressure);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_Potassium);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_Creatinine);
    assertNotNull(PropositionalConceptsSeries.Last_Previous_Creatinine);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_EGFR);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_Weight);
    assertNotNull(PropositionalConceptsSeries.Class_Of_Heart_Failure_With_Reduced_Ejection_Fraction);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_Heart_Rate);
    assertNotNull(PropositionalConceptsSeries.Has_Asthma);
    assertNotNull(PropositionalConceptsSeries.Has_Depression);
    assertNotNull(PropositionalConceptsSeries.Has_Kidney_Failure);
    assertNotNull(PropositionalConceptsSeries.Has_Hyperkalemia);
    assertNotNull(PropositionalConceptsSeries.Has_Alcohol_Abuse);
    assertNotNull(PropositionalConceptsSeries.Has_Heart_Failure_With_Reduced_Ejection_Fraction);
    assertNotNull(PropositionalConceptsSeries.On_Diltiazem);
    assertNotNull(PropositionalConceptsSeries.On_Dronedarone);
    assertNotNull(PropositionalConceptsSeries.On_Flecainide);
    assertNotNull(PropositionalConceptsSeries.On_NSAIDs);
    assertNotNull(PropositionalConceptsSeries.On_NSAIDS_Contraindicated_In_HFrEF);
    assertNotNull(PropositionalConceptsSeries.On_Propafenone);
    assertNotNull(PropositionalConceptsSeries.On_Rosiglitazone);
    assertNotNull(PropositionalConceptsSeries.On_Verapamil);
    assertNotNull(PropositionalConceptsSeries.On_Cilostazol);
    assertNotNull(PropositionalConceptsSeries.On_Itraconazole);
    assertNotNull(PropositionalConceptsSeries.On_Lisinopril);
    assertNotNull(PropositionalConceptsSeries.On_Enalapril);
    assertNotNull(PropositionalConceptsSeries.On_Captopril);
    assertNotNull(PropositionalConceptsSeries.On_Quinapril);
    assertNotNull(PropositionalConceptsSeries.On_Ramipril);
    assertNotNull(PropositionalConceptsSeries.On_Trandolapril);
    assertNotNull(PropositionalConceptsSeries.On_Fosinopril);
    assertNotNull(PropositionalConceptsSeries.On_Valsartan);
    assertNotNull(PropositionalConceptsSeries.On_Candesartan);
    assertNotNull(PropositionalConceptsSeries.On_Losartan);
    assertNotNull(PropositionalConceptsSeries.On_Carvedilol);
    assertNotNull(PropositionalConceptsSeries.On_Carvedilol_Phosphate);
    assertNotNull(PropositionalConceptsSeries.On_Metoprolol_Succinate);
    assertNotNull(PropositionalConceptsSeries.On_Bisoprolol);
    assertNotNull(PropositionalConceptsSeries.On_Spironolactone);
    assertNotNull(PropositionalConceptsSeries.On_Eplerenone);
    assertNotNull(PropositionalConceptsSeries.On_Beta_Blocker);
    assertNotNull(PropositionalConceptsSeries.On_ACE_Inhibitor);
    assertNotNull(PropositionalConceptsSeries.On_Angiotensin_Receptor_Blocker);
    assertNotNull(PropositionalConceptsSeries.On_Aldosterone_Antagonist);
    assertNotNull(PropositionalConceptsSeries.Has_Allergy_To_Beta_Blockers);
    assertNotNull(PropositionalConceptsSeries.Has_Allergy_To_Aldosterone_Antagonists);
    assertNotNull(
        PropositionalConceptsSeries.Has_Allergy_To_An_Angiotensin_Converting_Enzyme_ACE);
    assertNotNull(
        PropositionalConceptsSeries.Has_Allergy_To_An_Angiotensin_II_Receptor_Blockers_ARB);
    assertNotNull(PropositionalConceptsSeries.Age_Value_Of);
    assertNotNull(PropositionalConceptsSeries.Age_Within_Defined_Range_Is);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_Blood_Pressure_Value_Of);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_Potassium_Value_Of);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_Creatinine_Value_Of);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_EGFR_Value_Of);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_Weight_Value_Of);
    assertNotNull(PropositionalConceptsSeries.Most_Recent_Heart_Rate_Value_Of);
    assertNotNull(PropositionalConceptsSeries.Has_Asthma_Is);
    assertNotNull(PropositionalConceptsSeries.Has_Depression_Is);
    assertNotNull(PropositionalConceptsSeries.Has_Renal_Failure_Is);
    assertNotNull(PropositionalConceptsSeries.Has_Hyperkalemia_Is);
    assertNotNull(PropositionalConceptsSeries.Has_Alcohol_Abuse_Is);
    assertNotNull(PropositionalConceptsSeries.On_ACE_Inhibitor_Is);
    assertNotNull(PropositionalConceptsSeries.On_Beta_Blocker_Is);
    assertNotNull(PropositionalConceptsSeries.On_Angiotensin_II_Receptor_Blockers_Is);
    assertNotNull(PropositionalConceptsSeries.On_Aldosterone_Antagonist_Is);
    assertNotNull(PropositionalConceptsSeries.Has_Allergy_To_Beta_Blocker_Is);
    assertNotNull(PropositionalConceptsSeries.Has_Allergy_To_Aldosterone_Antagonist_Is);
    assertNotNull(
        PropositionalConceptsSeries.Has_Allergy_To_An_Angiotensin_Converting_Enzyme_ACE_Medication_Is);
    assertNotNull(PropositionalConceptsSeries.Has_Allergy_To_Angiotensin_II_Receptor_Blockers_Is);
    assertNotNull(PropositionalConceptsSeries.On_NSAIDs_Contraindicated_In_HFrEF_Is);
    assertNotNull(PropositionalConceptsSeries.Has_Heart_Failure_With_Reduced_Ejection_Fraction_Is);
    assertNotNull(PropositionalConceptsSeries.Total_Daily_Dose_Of_Beta_Blocker);
    assertNotNull(PropositionalConceptsSeries.Total_Daily_Dose_Of_ACE_Inhibitor);
    assertNotNull(PropositionalConceptsSeries.Total_Daily_Dose_Of_ARB);
    assertNotNull(PropositionalConceptsSeries.Total_Daily_Dose_Of_Aldosterone_Antagonist);
    assertNotNull(PropositionalConceptsSeries.Current_Weight);
  }


  @Test
  public void testMerAfibMostRecent() {

    assertNotNull(PropositionalConcepts.Patient);
    assertNotNull(PropositionalConcepts.Has_Atrial_Fibrillation);
    assertNotNull(
        PropositionalConcepts.Has_Bleeding_Disorder_Excluding_Hypercoagulative_Disorder);
    assertNotNull(PropositionalConcepts.History_Of_Central_Nervous_System_Bleeding);
    assertNotNull(PropositionalConcepts.History_Of_GI_Bleeding);
    assertNotNull(PropositionalConcepts.On_Anticoagulant);
    assertNotNull(PropositionalConcepts.History_Of_Congestive_Heart_Failure);
    assertNotNull(PropositionalConcepts.History_Of_Hypertension);
    assertNotNull(PropositionalConcepts.History_Of_Stroke);
    assertNotNull(PropositionalConcepts.History_Of_Transient_Ischemic_Attack);
    assertNotNull(PropositionalConcepts.History_Of_Thromboembolism);
    assertNotNull(PropositionalConcepts.History_Of_Coronary_Artery_Disease);
    assertNotNull(PropositionalConcepts.History_Of_Peripheral_Arterial_Disease);
    assertNotNull(PropositionalConcepts.Has_Diabetes_Mellitus);
    assertNotNull(PropositionalConcepts.Most_Recent_Blood_Pressure);
    assertNotNull(PropositionalConcepts.On_Dialysis);
    assertNotNull(PropositionalConcepts.On_Peritoneal_Dialysis);
    assertNotNull(PropositionalConcepts.On_Hemodialysis);
    assertNotNull(PropositionalConcepts.Has_Transplanted_Kidney);
    assertNotNull(PropositionalConcepts.Most_Recent_Creatinine);
    assertNotNull(PropositionalConcepts.Has_Cirrhosis);
    assertNotNull(PropositionalConcepts.Most_Recent_Bilirubin);
    assertNotNull(PropositionalConcepts.Most_Recent_AST_GOT);
    assertNotNull(PropositionalConcepts.Most_Recent_ALT_GPT);
    assertNotNull(PropositionalConcepts.Most_Recent_Alkaline_Phosphatase);
    assertNotNull(PropositionalConcepts.Prior_INR);
    assertNotNull(PropositionalConcepts.On_Antiplatelet_Agents);
    assertNotNull(PropositionalConcepts.On_NSAIDs);
//    assertNotNull(PropositionalConcepts.On_NSAIDs_Contraindicated_For_HFrEF);
    assertNotNull(PropositionalConcepts.Has_Alcohol_Abuse);
    assertNotNull(PropositionalConcepts.Has_Drug_Abuse);
    assertNotNull(PropositionalConcepts.Most_Recent_Amount_Of_Alcohol_Consumption);
    assertNotNull(PropositionalConcepts.On_Dialysis_Is);
    assertNotNull(PropositionalConcepts.On_Peritoneal_Dialysis_Is);
    assertNotNull(PropositionalConcepts.On_Hemodialysis_Is);
    assertNotNull(PropositionalConcepts.Has_Transplanted_Kidney_Is);
    assertNotNull(PropositionalConcepts.Most_Recent_Creatinine_Value_Of);
    assertNotNull(PropositionalConcepts.Has_Cirrhosis_Is);
    assertNotNull(PropositionalConcepts.Most_Recent_Bilirubin_Value_Of);
    assertNotNull(PropositionalConcepts.Most_Recent_AST_GOT_Value_Of);
    assertNotNull(PropositionalConcepts.Most_Recent_Alkaline_Phosphatase_Value_Of);
    assertNotNull(PropositionalConcepts.Has_Elevated_ALP_Is);
    assertNotNull(PropositionalConcepts.Has_Elevated_AST_Is);
    assertNotNull(PropositionalConcepts.Has_Elevated_ALT_Is);
    assertNotNull(PropositionalConcepts.Has_Elevated_Bilirubin_Is);
    assertNotNull(PropositionalConcepts.On_Antiplatelet_Agents_Is);
    assertNotNull(PropositionalConcepts.On_NSAID_Is);
    assertNotNull(PropositionalConcepts.Has_Alcohol_Abuse_Is);
    assertNotNull(PropositionalConcepts.Has_Drug_Abuse_Is);
    assertNotNull(PropositionalConcepts.Most_Recent_Amount_Of_Alcohol_Consumption_Value_Of);
    assertNotNull(PropositionalConcepts.Age_Value_Of);
    assertNotNull(PropositionalConcepts.Age_Within_Defined_Range_Kind_Of);
    assertNotNull(PropositionalConcepts.Age_Within_Defined_Range_Is);
    assertNotNull(PropositionalConcepts.Sex_Kind_Of);
    assertNotNull(PropositionalConcepts.History_Of_Congestive_Heart_Failure_Is);
    assertNotNull(PropositionalConcepts.History_Of_Hypertension_Is);
    assertNotNull(
        PropositionalConcepts.History_Of_Stroke_Transient_Ischemic_Attack_Or_Thromboembolism_Is);
    assertNotNull(PropositionalConcepts.History_Of_Vascular_Disease_Is);
    assertNotNull(PropositionalConcepts.Has_Diabetes_Mellitus_Is);
    assertNotNull(PropositionalConcepts.Most_Recent_Systolic_Blood_Pressure_Value_Of);
    assertNotNull(PropositionalConcepts.Has_Kidney_Disease_Is);
    assertNotNull(PropositionalConcepts.Has_Liver_Disease_Is);
    assertNotNull(PropositionalConcepts.History_Of_Stroke_Is);
    assertNotNull(PropositionalConcepts.Has_Labile_INR_Is);
    assertNotNull(PropositionalConcepts.Prior_Major_Bleeding_Or_Predisposition_To_Bleeding_Is);
    assertNotNull(PropositionalConcepts.On_Medication_Predisposing_To_Bleeding_Is);
    assertNotNull(PropositionalConcepts.History_Of_Alcohol_Or_Drug_Usage_Is);
    assertNotNull(PropositionalConcepts.Current_CHA2DS2_VASc_Score_Value_Of);
    assertNotNull(PropositionalConcepts.Current_HAS_BLED_Score_Value_Of);
  }


  @Test
  public void testMerHeartFailureMostRecent() {

    assertNotNull(PropositionalConcepts.Patient);
    assertNotNull(PropositionalConcepts.Most_Recent_Blood_Pressure);
    assertNotNull(PropositionalConcepts.Most_Recent_Potassium);
    assertNotNull(PropositionalConcepts.Most_Recent_Creatinine);
    assertNotNull(PropositionalConcepts.Last_Previous_Creatinine);
    assertNotNull(PropositionalConcepts.Most_Recent_EGFR);
    assertNotNull(PropositionalConcepts.Most_Recent_Weight);
    assertNotNull(PropositionalConcepts.Class_Of_Heart_Failure_With_Reduced_Ejection_Fraction);
    assertNotNull(PropositionalConcepts.Most_Recent_Heart_Rate);
    assertNotNull(PropositionalConcepts.Has_Asthma);
    assertNotNull(PropositionalConcepts.Has_Depression);
    assertNotNull(PropositionalConcepts.Has_Kidney_Failure);
    assertNotNull(PropositionalConcepts.Has_Hyperkalemia);
    assertNotNull(PropositionalConcepts.Has_Alcohol_Abuse);
    assertNotNull(PropositionalConcepts.Has_Heart_Failure_With_Reduced_Ejection_Fraction);
    assertNotNull(PropositionalConcepts.On_Diltiazem);
    assertNotNull(PropositionalConcepts.On_Dronedarone);
    assertNotNull(PropositionalConcepts.On_Flecainide);
    assertNotNull(PropositionalConcepts.On_NSAIDs);
    assertNotNull(PropositionalConcepts.On_Propafenone);
    assertNotNull(PropositionalConcepts.On_Rosiglitazone);
    assertNotNull(PropositionalConcepts.On_Verapamil);
    assertNotNull(PropositionalConcepts.On_Cilostazol);
    assertNotNull(PropositionalConcepts.On_Itraconazole);
    assertNotNull(PropositionalConcepts.On_Lisinopril);
    assertNotNull(PropositionalConcepts.On_Enalapril);
    assertNotNull(PropositionalConcepts.On_Captopril);
    assertNotNull(PropositionalConcepts.On_Quinapril);
    assertNotNull(PropositionalConcepts.On_Ramipril);
    assertNotNull(PropositionalConcepts.On_Trandolapril);
    assertNotNull(PropositionalConcepts.On_Fosinopril);
    assertNotNull(PropositionalConcepts.On_Valsartan);
    assertNotNull(PropositionalConcepts.On_Candesartan);
    assertNotNull(PropositionalConcepts.On_Losartan);
    assertNotNull(PropositionalConcepts.On_Carvedilol);
    assertNotNull(PropositionalConcepts.On_Carvedilol_Phosphate);
    assertNotNull(PropositionalConcepts.On_Metoprolol_Succinate);
    assertNotNull(PropositionalConcepts.On_Bisoprolol);
    assertNotNull(PropositionalConcepts.On_Spironolactone);
    assertNotNull(PropositionalConcepts.On_Eplerenone);
    assertNotNull(PropositionalConcepts.On_Beta_Blocker);
    assertNotNull(PropositionalConcepts.On_ACE_Inhibitor);
    assertNotNull(PropositionalConcepts.On_Angiotensin_Receptor_Blocker);
    assertNotNull(PropositionalConcepts.On_Aldosterone_Antagonist);
    assertNotNull(PropositionalConcepts.Has_Allergy_To_Beta_Blockers);
    assertNotNull(PropositionalConcepts.Has_Allergy_To_Aldosterone_Antagonists);
    assertNotNull(
        PropositionalConcepts.Has_Allergy_To_An_Angiotensin_Converting_Enzyme_ACE);
    assertNotNull(
        PropositionalConcepts.Has_Allergy_To_An_Angiotensin_II_Receptor_Blockers_ARB);
    assertNotNull(PropositionalConcepts.Age_Value_Of);
    assertNotNull(PropositionalConcepts.Age_Within_Defined_Range_Is);
    assertNotNull(PropositionalConcepts.Most_Recent_Blood_Pressure_Value_Of);
    assertNotNull(PropositionalConcepts.Most_Recent_Potassium_Value_Of);
    assertNotNull(PropositionalConcepts.Most_Recent_Creatinine_Value_Of);
    assertNotNull(PropositionalConcepts.Most_Recent_EGFR_Value_Of);
    assertNotNull(PropositionalConcepts.Most_Recent_Weight_Value_Of);
    assertNotNull(PropositionalConcepts.Most_Recent_Heart_Rate_Value_Of);
    assertNotNull(PropositionalConcepts.Has_Asthma_Is);
    assertNotNull(PropositionalConcepts.Has_Depression_Is);
    assertNotNull(PropositionalConcepts.Has_Renal_Failure_Is);
    assertNotNull(PropositionalConcepts.Has_Hyperkalemia_Is);
    assertNotNull(PropositionalConcepts.Has_Alcohol_Abuse_Is);
    assertNotNull(PropositionalConcepts.On_ACE_Inhibitor_Is);
    assertNotNull(PropositionalConcepts.On_Beta_Blocker_Is);
    assertNotNull(PropositionalConcepts.On_Angiotensin_II_Receptor_Blockers_Is);
    assertNotNull(PropositionalConcepts.On_Aldosterone_Antagonist_Is);
    assertNotNull(PropositionalConcepts.Has_Allergy_To_Beta_Blocker_Is);
    assertNotNull(PropositionalConcepts.Has_Allergy_To_Aldosterone_Antagonist_Is);
    assertNotNull(
        PropositionalConcepts.Has_Allergy_To_An_Angiotensin_Converting_Enzyme_ACE_Medication_Is);
    assertNotNull(PropositionalConcepts.Has_Allergy_To_Angiotensin_II_Receptor_Blockers_Is);
    assertNotNull(PropositionalConcepts.On_NSAIDs_Contraindicated_In_HFrEF_Is);
    assertNotNull(PropositionalConcepts.Has_Heart_Failure_With_Reduced_Ejection_Fraction_Is);
    assertNotNull(PropositionalConcepts.Total_Daily_Dose_Of_Beta_Blocker);
    assertNotNull(PropositionalConcepts.Total_Daily_Dose_Of_ACE_Inhibitor);
    assertNotNull(PropositionalConcepts.Total_Daily_Dose_Of_ARB);
    assertNotNull(PropositionalConcepts.Total_Daily_Dose_Of_Aldosterone_Antagonist);
  }

}
